language: python
sudo: false

python:
  - 2.6
  - 2.7

addons:
  apt:
    packages:
      - libssl0.9.8
      - libssl-dev
      - swig

install:
  - python setup.py install

script: python setup.py test

